version: 2.1
orbs:
  python: circleci/python@1.5.0

jobs:
  build:
    working_directory: ~/my-python-repo
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: run the main.py file
          command: python main.py
  test:
    working_directory: ~/my-python-repo
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run test
          command: pytest

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
